apiVersion: v1
kind: Pod
metadata:
  name: jump
spec:
  containers:
  - name: shell
    image: gosharplite/ubuntu:v2
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
