apiVersion: v1
kind: Pod
metadata:
  name: constraint-pod
spec:
  containers:
  - name: main-app
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
