apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  containers:
  - name: main-service
    image: owensengoku/simpleservice:v0.5.2
    ports:
    - containerPort: 9876
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
  - name: shell
    image: gosharplite/ubuntu:v2
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"

