apiVersion: v1
kind: Pod
metadata:
  name: label-example-1
  labels:
    env: dev
spec:
  containers:
  - name: main-app
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876