apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: privileged
  creationTimestamp: null
  name: jump
  selfLink: /api/v1/namespaces/test/pods/jump
spec:
  containers:
  - command:
    - bin/bash
    - -c
    - sleep 10000
    image: gosharplite/ubuntu:v2
    imagePullPolicy: IfNotPresent
    name: shell
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 500m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-w2t9s
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: poc-kbn-vm08
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-w2t9s
    secret:
      defaultMode: 420
      secretName: default-token-w2t9s
status:
  phase: Pending
  qosClass: Guaranteed
